# Generated by Django 4.2.2 on 2024-07-22 19:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='email address')),
                ('surname', models.CharField(help_text='Укажите фамилию', max_length=100, verbose_name='Фамилия')),
                ('name', models.CharField(help_text='Укажите имя', max_length=100, verbose_name='Имя')),
                ('patronymic', models.CharField(help_text='Укажите отчество', max_length=100, verbose_name='Отчество')),
                ('comment', models.TextField(blank=True, help_text='Добавьте комментарий', null=True, verbose_name='Комментарий')),
            ],
            options={
                'verbose_name': 'Клиент',
                'verbose_name_plural': 'Клиенты',
                'ordering': ['id'],
            },
        ),
    ]
