# Generated by Django 4.2.2 on 2024-07-27 18:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import relativedeltafield.fields


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('clients', '0001_initial'),
        ('mailings', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Mailing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата и время создания')),
                ('first_attempt_at', models.DateTimeField(blank=True, null=True, verbose_name='Дата и время первой рассылки')),
                ('last_attempt_at', models.DateTimeField(blank=True, null=True, verbose_name='Дата и время последней попытки')),
                ('started_at', models.DateTimeField(verbose_name='Дата и время начала')),
                ('completed_at', models.DateTimeField(verbose_name='Дата и время завершения')),
                ('sending_interval', relativedeltafield.fields.RelativeDeltaField(verbose_name='Интервал рассылки')),
                ('frequency', models.CharField(choices=[('DAILY', 'every day'), ('WEEKLY', 'every week'), ('MONTHLY', 'every_month')], default='DAILY', max_length=8, verbose_name='Частота')),
                ('status', models.CharField(choices=[('CREATED', 'создана'), ('SENDING', 'запущена'), ('COMPLETED', 'завершена')], default='CREATED', max_length=16, verbose_name='Статус')),
                ('clients', models.ManyToManyField(related_name='mailings', to='clients.client', verbose_name='Клиенты')),
                ('message', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mailings', to='mailings.message', verbose_name='Сообщение')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mailings', to=settings.AUTH_USER_MODEL, verbose_name='Создатель')),
            ],
            options={
                'verbose_name': 'Рассылка',
                'verbose_name_plural': 'Рассылки',
            },
        ),
        migrations.CreateModel(
            name='MailingAttempt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('attempt_at', models.DateTimeField(blank=True, null=True, verbose_name='Дата и время попытки')),
                ('status', models.CharField(choices=[('OK', 'успешно'), ('FAILED', 'не успешно')], max_length=6, verbose_name='Статус')),
                ('server_response', models.CharField(blank=True, max_length=128, null=True, verbose_name='Ответ почтового сервера')),
                ('mailing', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='attempts', to='mailings.mailing', verbose_name='Рассылка')),
            ],
        ),
    ]
