# Generated by Django 4.2.2 on 2024-07-28 10:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mailings', '0002_mailing_mailingattempt'),
    ]

    operations = [
        migrations.AddField(
            model_name='mailing',
            name='name',
            field=models.CharField(default='mail', max_length=255, verbose_name='Название рассылки'),
            preserve_default=False,
        ),
    ]
