# Generated by Django 4.2.2 on 2024-07-28 11:42

from django.db import migrations
import relativedeltafield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('mailings', '0003_mailing_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mailing',
            name='sending_interval',
            field=relativedeltafield.fields.RelativeDeltaField(blank=True, null=True, verbose_name='Интервал рассылки'),
        ),
    ]
