# Generated by Django 4.2.2 on 2024-07-28 20:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mailings', '0004_alter_mailing_sending_interval'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='mailing',
            options={'permissions': [('can_ban_mailing', 'Can ban mailing')], 'verbose_name': 'Рассылка', 'verbose_name_plural': 'Рассылки'},
        ),
        migrations.AddField(
            model_name='mailing',
            name='is_banned',
            field=models.BooleanField(default=False, verbose_name='Заблокирована ли рассылка'),
        ),
    ]
